#!/usr/bin/env python3
"""
test_instrument_lockstep.py — N1/N3: guard against drift between
questionnaire_instrument_source.md, questionnaire_items.csv, the shared
config, student_start.sh, and make_persona.py.

Checks (all stdlib, no network, no browser):
  1. questionnaire_items.csv has exactly EXPECTED_ITEMS rows.
  2. item codes unique and matching ^[A-Z]{1,4}\\d{1,3}$; no EX0x rows.
  3. constraint=1 exactly on VC01–VC05.
  4. options non-empty for single_select/multi_select, empty for
     likert5/short_text/long_text.
  5. construct blocks contiguous (each construct appears in one run).
  6. EXPECTED_ITEMS agrees across dtlab_config.env and the fallback
     literal in provisioning/student_start.sh.
  7. The ID pattern in build_form.gs accepts/rejects the same samples as
     the shared DTLAB_ID_PATTERN.
  8. N3: a persona generated by make_persona.py from a fabricated
     responses row yields exactly EXPECTED_ITEMS lines matching the
     '^- \\*\\*' pattern student_start.sh counts.

Run from repo root:  python3 tests/test_instrument_lockstep.py
"""

import csv
import importlib.util
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CSV_PATH = REPO / "questionnaire" / "questionnaire_items.csv"
CODE_RE = re.compile(r"^[A-Z]{1,4}\d{1,3}$")


def _load_agent_hidden_items():
    """The ONE authoritative exclusion set lives in make_persona.py."""
    spec = importlib.util.spec_from_file_location(
        "make_persona", REPO / "questionnaire" / "make_persona.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return set(mod.AGENT_HIDDEN_ITEMS)

failures = []


def check(cond, msg):
    if cond:
        print(f"  PASS: {msg}")
    else:
        print(f"  FAIL: {msg}")
        failures.append(msg)


def load_config():
    cfg = {}
    for raw in (REPO / "dtlab_config.env").read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        cfg[k.strip()] = v.strip().strip("'\"")
    return cfg


def main():
    cfg = load_config()
    expected = int(cfg.get("DTLAB_EXPECTED_ITEMS", "115"))

    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))

    # 1–2: row count, code shape
    check(len(rows) == expected,
          f"CSV has exactly {expected} rows (got {len(rows)})")
    codes = [r["item_code"] for r in rows]
    check(len(codes) == len(set(codes)), "item codes are unique")
    bad = [c for c in codes if not CODE_RE.fullmatch(c)]
    check(not bad, f"all codes match ^[A-Z]{{1,4}}\\d{{1,3}}$ (bad: {bad[:5]})")
    check(not any(c.startswith("EX0") for c in codes),
          "no EX0x placeholder rows")

    # 3: constraint flags
    flagged = [r["item_code"] for r in rows
               if (r.get("constraint") or "").strip() == "1"]
    check(flagged == ["VC01", "VC02", "VC03", "VC04", "VC05"],
          f"constraint=1 exactly on VC01–VC05 (got {flagged})")

    # 4: options discipline
    bad_opts = []
    for r in rows:
        t, o = r["response_type"], (r.get("options") or "").strip()
        if t in ("single_select", "multi_select") and not o:
            bad_opts.append((r["item_code"], "missing options"))
        if t in ("likert5", "short_text", "long_text") and o:
            bad_opts.append((r["item_code"], "unexpected options"))
        if t in ("single_select", "multi_select") and o and \
                any(not part.strip() for part in o.split("|")):
            bad_opts.append((r["item_code"], "empty pipe segment"))
    check(not bad_opts, f"options match response_type contract ({bad_opts[:5]})")

    # 5: contiguous construct blocks
    seen_blocks, prev = [], None
    for r in rows:
        if r["construct"] != prev:
            seen_blocks.append(r["construct"])
            prev = r["construct"]
    check(len(seen_blocks) == len(set(seen_blocks)),
          "construct blocks are contiguous (no construct appears twice)")

    # 6: EXPECTED_ITEMS lockstep with student_start.sh's fallback literal
    start_sh = (REPO / "provisioning" / "student_start.sh").read_text()
    m = re.search(r'EXPECTED_ITEMS="\$\{DTLAB_EXPECTED_ITEMS:-(\d+)\}"',
                  start_sh)
    check(m is not None and int(m.group(1)) == expected == len(rows),
          "EXPECTED_ITEMS fallback in student_start.sh == config == CSV rows")

    # 6b: agent-hidden exclusion set (B10): exactly {PR02, PR08}, all in
    # the instrument, and student_start.sh's rendered-count gate subtracts
    # exactly that many items
    hidden = _load_agent_hidden_items()
    check(hidden == {"PR02", "PR08"},
          f"make_persona.AGENT_HIDDEN_ITEMS is exactly {{PR02, PR08}} "
          f"(got {sorted(hidden)})")
    check(hidden <= set(codes),
          "every agent-hidden item exists in the instrument")
    hm = re.search(r"AGENT_HIDDEN_COUNT=(\d+)", start_sh)
    check(hm is not None and int(hm.group(1)) == len(hidden),
          "student_start.sh AGENT_HIDDEN_COUNT == len(AGENT_HIDDEN_ITEMS)")
    rendered = expected - len(hidden)

    # 7: build_form.gs ID pattern semantically in sync with the config
    gs = (REPO / "questionnaire" / "build_form.gs").read_text()

    # 7a: the two consent checkboxes (docs/CONSENT_AND_DATA_USE.md >
    # "What you confirm") sit at the top of the Form build — layer 1 of
    # the layered consent capture (research_protocol §3)
    check("Understanding — I understand" in gs
          and "Consent — I consent" in gs,
          "build_form.gs carries both consent checkboxes (Understanding "
          "+ Consent)")
    check("CONSENT_AND_DATA_USE" in gs,
          "build_form.gs points at the consent & data-use sheet")
    gm = re.search(r"requireTextMatchesPattern\('([^']+)'\)", gs)
    check(gm is not None, "build_form.gs contains an ID validation pattern")
    if gm:
        gs_re = re.compile(gm.group(1).replace("\\\\", "\\"))
        cfg_re = re.compile(cfg["DTLAB_ID_PATTERN"])
        samples = [("DT2026-042", True), ("DT2026-999", True),
                   ("DT26-042", False), ("DTX026-042", False)]
        ok = all(bool(gs_re.fullmatch(s)) == bool(cfg_re.fullmatch(s)) == want
                 for s, want in samples)
        check(ok, "build_form.gs ID pattern and DTLAB_ID_PATTERN agree "
                  "on sample IDs")

    # 8 (content lockstep): parse §2 of the authoritative source document
    # and diff codes/order/constraints/types/options/wording against the
    # CSV — makes "source doc and CSV never diverge" an enforced property.
    src = (REPO / "questionnaire" /
           "questionnaire_instrument_source.md").read_text(encoding="utf-8")
    body = src.split("## 2. The instrument", 1)[1].split(
        "## 3. References", 1)[0]

    def norm(s):
        # typographic normalization only — dashes are flattened to
        # hyphens in the CSV transfer (AUTHORING_GUIDE convention), and
        # quote/ellipsis glyphs vary; anything beyond this is real drift
        s = (s.replace("’", "'").replace("‘", "'")
             .replace("“", '"').replace("”", '"')
             .replace("…", "...")
             .replace("–", "-").replace("—", "-").replace("−", "-"))
        return re.sub(r"\s+", " ", s).strip()

    TYPE_RE = re.compile(
        r"—\s*(single_select|multi_select|likert5|short_text|long_text)"
        r"[^\[\n]*(?:\[([^\]]*)\])?")
    ITEM_RE = re.compile(
        r"^- \*\*(?P<code>[A-Z]{1,4}\d{1,3})"
        r"(?P<constr> \[CONSTRAINT\])?\*\*\s*(?P<rest>.+)$")
    src_items, block_type, block_opts = {}, None, None
    for line in body.splitlines():
        if line.startswith("### Block"):
            tm = TYPE_RE.search(line)
            block_type = tm.group(1) if tm else None
            block_opts = ([o.strip() for o in tm.group(2).split(";")]
                          if tm and tm.group(2) else None)
            continue
        m = ITEM_RE.match(line.strip())
        if not m:
            continue
        rest = re.sub(r"\*\([^)]*\)\*\s*$", "", m.group("rest")).strip()
        tm = TYPE_RE.search(rest)
        if tm:
            itype = tm.group(1)
            iopts = ([o.strip() for o in tm.group(2).split(";")]
                     if tm.group(2) else None)
            text = rest[:tm.start()].strip(" —")
        else:
            itype, iopts = block_type, block_opts
            text = rest
        src_items[m.group("code")] = {
            "constraint": bool(m.group("constr")),
            "type": itype, "opts": iopts, "text": norm(text)}

    check(list(src_items) == codes,
          f"source-doc §2 codes match CSV codes and order "
          f"({len(src_items)} parsed)")
    src_constr = [c for c, it in src_items.items() if it["constraint"]]
    check(src_constr == flagged,
          f"source-doc [CONSTRAINT] markers == CSV constraint=1 "
          f"({src_constr})")
    diffs = []
    for r in rows:
        it = src_items.get(r["item_code"])
        if it is None:
            continue
        if it["type"] and it["type"] != r["response_type"]:
            diffs.append((r["item_code"], "type",
                          f"{it['type']} != {r['response_type']}"))
        if it["opts"] is not None:
            csv_opts = [o.strip() for o in
                        (r.get("options") or "").split("|")]
            if [norm(o) for o in it["opts"]] != [norm(o)
                                                 for o in csv_opts]:
                diffs.append((r["item_code"], "options",
                              f"{it['opts'][:3]}... != {csv_opts[:3]}..."))
        if it["text"] and norm(it["text"]).lower() not in \
                norm(r["question"]).lower():
            diffs.append((r["item_code"], "wording",
                          it["text"][:60]))
    check(not diffs,
          f"CSV wording/options/types match source-doc §2 "
          f"({len(diffs)} diffs; first: {diffs[:3]})")

    # 9 (N3): fabricate a Form response row, run make_persona.py, count the
    # exact pattern student_start.sh greps ('^- **CODE** ...').
    with tempfile.TemporaryDirectory() as tmp:
        td = Path(tmp)
        id_header = "Your course-issued participant ID (e.g. DT2026-042)"
        headers = ["Timestamp", id_header] + \
                  [f"{r['item_code']}. {r['question']}" for r in rows]
        row = ["2026-09-01 10:00:00", "DT2026-042"] + \
              [_fake_answer(r) for r in rows]
        with open(td / "responses.csv", "w", newline="",
                  encoding="utf-8") as f:
            w = csv.writer(f)
            w.writerow(headers)
            w.writerow(row)
        r = subprocess.run(
            check=False,
            args=[sys.executable,
                  str(REPO / "questionnaire" / "make_persona.py"),
             "--items", str(CSV_PATH), "--responses", str(td / "responses.csv"),
             "--student-id", "DT2026-042", "--outdir", str(td)],
            capture_output=True, text=True)
        check(r.returncode == 0,
              f"make_persona.py succeeds on fabricated row ({r.stderr.strip()[:200]})")
        persona = td / "persona_survey.md"
        if persona.exists():
            ptext = persona.read_text()
            n = sum(1 for line in ptext.splitlines()
                    if re.match(r"^- \*\*", line))
            check(n == rendered,
                  f"persona_survey.md has {rendered} agent-visible '- **' "
                  f"item lines ({expected}-item instrument minus "
                  f"{len(hidden)} research-only; got {n}) — the count "
                  "student_start.sh checks")
            leaked = [c for c in hidden if f"**{c}**" in ptext]
            check(not leaked,
                  f"agent-hidden items absent from persona_survey.md "
                  f"(leaked: {leaked})")
            pcsv = (td / "persona_survey.csv").read_text()
            kept = [c for c in hidden if f",{c}," in pcsv]
            check(sorted(kept) == sorted(hidden),
                  "agent-hidden items still present in the research CSV")
            n_ans = sum(1 for line in ptext.splitlines()
                        if "(no answer)" in line)
            check(n_ans == 0, f"all fabricated answers mapped ({n_ans} unmapped)")
        else:
            check(False, "persona_survey.md was generated")

    print()
    if failures:
        print(f"{len(failures)} FAILURE(S)")
        return 1
    print("Instrument lockstep: all checks pass.")
    return 0


def _fake_answer(item):
    t = item["response_type"]
    opts = (item.get("options") or "").split("|")
    if t == "likert5":
        return "4 - Agree a little"
    if t in ("single_select", "multi_select") and opts and opts[0].strip():
        return opts[0].strip()
    return "test answer"


if __name__ == "__main__":
    sys.exit(main())
